### PR TITLE
sync with maorfr/cain and add backup tag support

### PR DESCRIPTION
**Pull request by nvtkaszpir**
- sync with maorfr/cain master
- add backup tag support from nvtkaszpir/cain backup-tag

### CODE REVIEW

**Review by aharonh — CHANGES_REQUESTED** [review]
I do not think we should be switching to the maorfr image in this repo.

**Comment by nvtkaszpir** [comment]
I'm more interested in just supporting creating backups with a tag, without the other commits.
If you are willing to accept such PR then I can make a new one and close this one.

**Comment by nvtkaszpir** [comment]
> hi @nvtkaszpir, thanks for the effort! I do not think we should be switching to the maorfr image in this repo. we need to cherry pick only the changes that are relevant for this repo in this commit: [417aff7](https://github.com/nuvo/cain/commit/417aff78b54a2ec34e76913e2b39edb4e7f304f3)

ah yeah, sorry haven't noticed that.

**Comment by aharonh** [comment]
as you wish, any effort is appreciated! 

thanks!

**Comment by nvtkaszpir** [comment]
OK, I'll extract it as separate PR, then.

**Pull request closed without merging**
